const _TOKEN =
  // "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZjNGI0YjZmZDIyODAwMTUzZmRiY2YiLCJpYXQiOjE2MTc3MDk4OTksImV4cCI6MTYxODkxOTQ5OX0.F_D6JHoKkrmlqFZN5B94Vr8OXMJeR5tJRoUGb6cK02o";
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZjMjcyMTZmZDIyODAwMTUzZmRiY2MiLCJpYXQiOjE2MTgxODEyMDksImV4cCI6MTYxOTM5MDgwOX0.gnpuXA-s6oKUKwjIC4ZHU5EQg5LGtY1Ac1R2tOKr8AI";

export const headers = {
  "Content-Type": "application/json",
  Authorization: `Bearer ${_TOKEN}`,
};
