name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sk-linkedin-clone"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix backend main`:refs/heads/main --force